file:
  basePath: D:/Downloads
  uploadDir: /uploads
  tempDir: /temp
  clickBoardPicName: cbpn
spring:
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8081

#logging:
#  level:
#    com.example.filerouter.controller: debug
#    com.example.filerouter.service.UpService: debug